### ISSUE TITLE
CommonJS/ESM Export Mismatch

### ISSUE THREAD

**Issue by awmichel** [Dig-Doug/rules_typescript_proto#12]
## Description
`change_import_style.ts` is converting the JS output from protoc into CommonJS while giving the output file a `.mjs` extension. It is my understanding that the `.mjs` extension is for ECMAScript modules which use [this syntax](https://tc39.es/ecma262/#sec-exports).

[This MDN documentation](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Modules) confirms the `.mjs` + ECMAScript module syntax.

## Errors seen
 This causes issues when using Rollup which expects `.mjs` files to use the ECMAScript module syntax and is why the examples in this repo have to add `.mjs` to the extensions for `rollup-plugin-commonjs`.

## Minimal Reproduction
The test in this repo is a good minimal example of the problem, specifically these lines:

https://github.com/Dig-Doug/rules_typescript_proto/blob/ebf191aec9ef0977d7352a6644e9cd91615d3693/src/change_import_style.ts#L65-L80

https://github.com/Dig-Doug/rules_typescript_proto/blob/ebf191aec9ef0977d7352a6644e9cd91615d3693/test/rollup.config.js#L5-L7

## Your Environment
N/A

#### What operating system are you using?
N/A

#### What version of bazel are you using?
N/A

#### What version of the library are you using?
```python
http_archive(
    name = "rules_typescript_proto",
    sha256 = "224a98a044a726f04883392a68a2f0cf0a277dc0d3150f00b71e430ad53f583e",
    strip_prefix = "rules_typescript_proto-ebf191aec9ef0977d7352a6644e9cd91615d3693",
    urls = [
        "https://github.com/Dig-Doug/rules_typescript_proto/archive/ebf191aec9ef0977d7352a6644e9cd91615d3693.tar.gz",
    ],
)
```

## Any other comments?
I will be working on an MR to fix the issue for our internal use in the coming days, but wanted to open an issue for discussion prior. The real question here is whether to maintain the existing behavior (using `.mjs` with CommonJS export syntax) or *fix* the import style script to use ECMAScript export syntax. Fixing the export syntax may cause issues for end-users who have built other workarounds for this issue.

**Comment by Dig-Doug** [comment]
Thanks for the detailed description, this looks like a bug that we should fix.

I'm not concerned about breaking existing users since this seems like a step in the right direction -- especially if it fixes issues with rollup.

I'm happy to accept a PR to fix this.

**Comment by eordano** [comment]
🙏 my workaround is to explicitly require with rollup the _lib files

**Comment by thesayyn** [comment]
Also, you guys can look at my protoc plugin that generates pure typescript files from proto files.

https://github.com/thesayyn/protoc-gen-ts
