### ISSUE TITLE
Build dependence of ts proto

### ISSUE THREAD

**Issue by liuheng-pony** [Dig-Doug/rules_typescript_proto#121]
## Description
Rule `typescript_proto_library` does not build deps protos but only srcs protos. Anything I'm doing wrong?

We were using `protoc` to generate js/ts proto, and changing to use bazel now. We used to have a python script to solve the problem, but I don't have any idea with it now. Do you have any suggestions for me to deal with it? It is hard to asks developer who edit proto files to help update the ts BUILD file. Since we have a huge project with multiple languages sharing the protos.

#### What operating system are you using?
Ubuntu 16.04

#### What version of bazel are you using?
bazel 2.2.0

**Comment by Dig-Doug** [comment]
Hi,

I'm not sure I completely understand your question.

This library will generate JavaScript and TypeScript files for all of the transitive dependencies. For example, if you take a look [here](https://github.com/Dig-Doug/rules_typescript_proto/blob/master/test/proto/BUILD.bazel#L24), the `pizza_service_ts_proto` rule will also generate files for the dependencies declared by the `proto_library`. You do not need to define `typescript_proto_library` rules for the dependencies.

If you're using bazel to build protos for multiple languages, there shouldn't be any behavior differences between `typescript_proto_library` and the proto rules for other languages, e.g. `java_proto_library`. (If there is then it's a bug).

If you're migrating from non-bazel to bazel, you will need to define a `proto_library` structure for your entire codebase. The `proto_library` rules are shared by all languages for generating code. There are existing tools that may help to generate the structure, e.g. buildozer, gazelle, depending on what languages you're using.

Hopefully this helps.

**Comment by liuheng-pony** [comment]
I'm not sure any mistake i took, But when I build `pizza_service_ts_proto` the dependencies are not generated. 
```
$ bazel build //test/proto:pizza_service_ts_proto 
INFO: Analyzed target //test/proto:pizza_service_ts_proto (350 packages loaded, 7299 targets configured).
INFO: Found 1 target...
Target //test/proto:pizza_service_ts_proto up-to-date:
  bazel-bin/test/proto/pizza_service_pb.js
  bazel-bin/test/proto/pizza_service_pb_service.js
  bazel-bin/test/proto/pizza_service_pb.mjs
  bazel-bin/test/proto/pizza_service_pb_service.mjs
  bazel-bin/test/proto/pizza_service_pb.d.ts
  bazel-bin/test/proto/pizza_service_pb_service.d.ts
INFO: Elapsed time: 57.953s, Critical Path: 11.57s
INFO: 184 processes: 183 linux-sandbox, 1 worker.
INFO: Build completed successfully, 207 total actions
```

```
$ ls bazel-bin/test/proto/ -lR
bazel-bin/test/proto/:
total 112
drwxrwxr-x 2 liuheng liuheng  4096 7月   7 21:22 common
-r-xr-xr-x 1 liuheng liuheng  2482 7月   7 21:23 pizza_service_pb.d.ts
-r-xr-xr-x 1 liuheng liuheng 13025 7月   7 21:23 pizza_service_pb.js
-r-xr-xr-x 1 liuheng liuheng 12667 7月   7 21:23 pizza_service_pb.mjs
-r-xr-xr-x 1 liuheng liuheng  2395 7月   7 21:23 pizza_service_pb_service.d.ts
-r-xr-xr-x 1 liuheng liuheng  2071 7月   7 21:23 pizza_service_pb_service.js
-r-xr-xr-x 1 liuheng liuheng  1641 7月   7 21:23 pizza_service_pb_service.mjs
-r-xr-xr-x 1 liuheng liuheng   407 7月   7 21:22 pizza_service_proto-descriptor-set.proto.bin

bazel-bin/test/proto/common:
total 24
-r-xr-xr-x 1 liuheng liuheng 238 7月   7 21:22 delivery_person_proto-descriptor-set.proto.bin
-r-xr-xr-x 1 liuheng liuheng 255 7月   7 21:22 pizza_proto-descriptor-set.proto.bin
```

**Comment by Dig-Doug** [comment]
Try:

```bash
bazel build //test:commonjs_test 
ls bazel-bin/test/proto/common
```

If you actually use the library as a dep to a binary, etc., all the transitive deps will be included.

**Comment by liuheng-pony** [comment]
Thanks a lot, Doug. I made it. It means, it should be used in a `ts_library`. I was trying to use it in webpack directly.
