### ISSUE TITLE
Bump build_bazel_rules_nodejs version to 2.x

### ISSUE THREAD

**Issue by yihanzhen** [Dig-Doug/rules_typescript_proto#127]
Any chance you could bump the version of `build_bazel_rules_nodejs` to `2.x.x`? (latest is [2.0.3](https://github.com/bazelbuild/rules_nodejs/tags))

Bazel doesn't allow depending on different major versions of a dependency.

Thanks!

**Comment by Dig-Doug** [comment]
Can you submit a PR?
