### ISSUE TITLE
'packages/typescript' is not a package

### ISSUE THREAD

**Issue by jamelmerhaby** [Dig-Doug/rules_typescript_proto#138]
## Description
Followed the setup instructions by first adding rules_nodejs, and rules_proto, then followed the instructions to add rules_typescript_proto to my WORKSPACE, and updated my BUILD file with a typescript_proto_library, but I cannot get a successful build. I tried copying dependencies from the rules_typescript_proto's package.json file, but that did not help either.

## Errors seen
every rule of type proto_library implicitly depends upon the target '@rules_typescript_proto//src:change_import_style', but this target could not be found because of: error loading package '@rules_typescript_proto//src': Label '@build_bazel_rules_nodejs//packages/typescript:index.bzl' is invalid because 'packages/typescript' is not a package; perhaps you meant to put the colon here: '@build_bazel_rules_nodejs//:packages/typescript/index.bzl'?

## Minimal Reproduction
*Please create and share a minimal reproduction of the issue. You can create a GitHub repository and share the link. If there are additional steps or commands needed to reproduce the problem, please add them here or to the repository.*

https://github.com/jamelmerhaby/goose

## Your Environment
*Please answer the questions below*

#### What operating system are you using?
macOS 11.1 - Big Sur

#### What version of bazel are you using?
*Run `bazel version` and paste contents here*
Build label: 3.5.0-homebrew
Build target: bazel-out/darwin-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Thu Sep 3 00:54:35 2020 (1599094475)
Build timestamp: 1599094475
Build timestamp as int: 1599094475

#### What version of the library are you using?
sha256 = "8e16f3c3d2ed8abc8935b9d177f056d1920b70ac1aff94477aa9761362982123"

## Any other comments?
I tried adding these to an existing repo, but ran into the same problem. The repro I setup and linked in this bug is as small as possible and I tried to follow instructions to a T with the exception of trying to add dependencies to package.json. I verified that I can run the proto_library target just fine, but whenever I try to build a typescript_proto_library target, I get the build errors that I mentioned above. I am confident at least that the proto_library target is fine and the nodejs rules are fine because I tried running bazel build along the way.

**Comment by Dig-Doug** [comment]
Looks like the docs are ahead of version `1.0.0`. I'm creating a new release now, if you update to it then it will work.

Fixed by #139

**Comment by jamelmerhaby** [comment]
Thanks for getting to this so quickly, I really appreciate that. I thought for sure that I missed a step.

I got excited and looked at your fix and applied it to my toy repo and ran into a slight issue. Bazel suggested that I use a different SHA256 hash than the one in the updated README. Everything worked perfectly once I switched the hash. 

Thanks again, this project is incredibly helpful!!!
