### ISSUE TITLE
*.proto files cannot be in a different directory than the BUILD file

### ISSUE THREAD

**Issue by pfgallagher** [Dig-Doug/rules_typescript_proto#142]
## Description
If the *.proto provided to proto_library's `srcs` is not in the same directory as the BUILD file, the below error gets thrown. Basically, `fs` is looking for `bazel-out/k8-fastbuild/bin/test/proto/naming_styles_pb.js` when it should be (in the repro's case) looking for `bazel-out/k8-fastbuild/bin/test/proto/repro_example/naming_styles_pb.js`.

 This is inconsistent from other language implementations (tested with rules_proto_grpc's cpp_proto_library, java_proto_library, and python_proto_library, to name a few). This causes issues if you try to use directories for versioning (see [the tree here](https://docs.buf.build/lint-rules/#file_layout) for an example). Adding an additional BUILD file to the directory with the *.proto is not a viable workaround because proto_library then throws an error if a subpackage is provided to `srcs`. Moving the BUILD file inside the directory with the *.proto should theoretically work, but somewhat defeats the purpose of versioning in this manner.

Presumably, the other language implementations in rules_proto_grpc would be good starting points for a fix. I'm happy to help out where I can, but I admittedly don't have a ton of experience writing Bazel rules. So, it probably makes sense to defer this to @Dig-Doug or anyone else interested in taking a look. Thank you very much!

## Errors seen
```
Error: ENOENT: no such file or directory, open 'bazel-out/k8-fastbuild/bin/test/proto/naming_styles_pb.js'
    at Object.openSync (fs.js:440:3)
    at Object.readFileSync (fs.js:342:35)
    at main (/home/gitpod/.cache/bazel/_bazel_gitpod/<hash removed>/sandbox/processwrapper-sandbox/17/execroot/rules_typescript_proto/bazel-out/host/bin/src/change_impo
rt_style.sh.runfiles/rules_typescript_proto/src/change_import_style.js:26:36)
    at /home/gitpod/.cache/bazel/_bazel_gitpod/<hash removed>/sandbox/processwrapper-sandbox/17/execroot/rules_typescript_proto/bazel-out/host/bin/src/change_import_sty
le.sh.runfiles/rules_typescript_proto/src/change_import_style.js:106:5
    at /home/gitpod/.cache/bazel/_bazel_gitpod/<hash removed>/sandbox/processwrapper-sandbox/17/execroot/rules_typescript_proto/bazel-out/host/bin/src/change_import_style.sh.runfiles/rules_typescript_proto/src/change_import_style.js:3:17
    at Object.<anonymous> (/home/gitpod/.cache/bazel/_bazel_gitpod/<hash removed>/sandbox/processwrapper-sandbox/17/execroot/rules_typescript_proto/bazel-out/host/bin/src/change_import_style.sh.runfiles/rules_typescript_proto/src/change_import_style.js:9:3)
    at Module._compile (internal/modules/cjs/loader.js:956:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
    at Module.load (internal/modules/cjs/loader.js:812:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
```

## Minimal Reproduction
[Repro fork](https://github.com/pfgallagher/rules_typescript_proto/commit/0441d2676178c73bd7809b74583cb6e4aabc7abb)

#### What operating system are you using?
Ubuntu 20.04.1 LTS (Focal Fossa)

#### What version of bazel are you using?
3.5.0

#### What version of the library are you using?
Latest

**Comment by Dig-Doug** [comment]
Thanks for reporting this. I tried fixing this in #143. If you have a chance, try it out and let me know if you run into any issues.

**Comment by pfgallagher** [comment]
Anytime! And thanks for coming up with a fix so quickly! Very much appreciated!

I'm going to give it a shot here in a bit and will, of course, let you know if there are any issues. I'm happy to go through your changes, too, if it would be useful!

**Comment by pfgallagher** [comment]
Following up on this: it appears to be working correctly!
