### ISSUE TITLE
Issues building under Bazel 4.1.0

### ISSUE THREAD

**Issue by Mista-Ree** [Dig-Doug/rules_typescript_proto#150]
## Description
After a recent upgrade to Bazel version 4.1.0, we noticed that targets which depend on `rules_typescript_proto` would no longer build. We suspect this was due to a change in something internal to Bazel which `ts_library` depended upon.

I wonder if using `ts_project` in place of `ts_library` would have an effect on this? The upstream Bazel typescript rules recommend using `ts_project` in place of `ts_library` for new code anyway.

## Errors seen
```bash
ERROR: <redacted>/rules_typescript_proto/src/BUILD.bazel:15:11: Compiling TypeScript (devmode) @rules_typescript_proto//src:change_import_style_lib [for host] failed: (Exit 1): tsc_wrapped.sh failed: error executing command bazel-out/host/bin/external/rules_typescript_proto_deps/@bazel/typescript/bin/tsc_wrapped.sh @@bazel-out/host/bin/external/rules_typescript_proto/src/change_import_style_lib_es5_tsconfig.json
Compilation failed Error: ENOENT: no such file or directory, open '<redacted>/rules_typescript_proto_deps/node_modules/typescript/lib/lib.es2021.string.d.ts'
```
(We are using a newer version of typescript in our build and I suspect that's what's causing the error above - though it's unclear to me what's changed in Bazel from 4.0.0 to 4.1.0 that could cause this.)

## Minimal Reproduction
Use 'rules_typescript_proto' in a project that uses the latest version of Typescript and Bazel 4.1.0.

#### What operating system are you using?
OSX 10.15.7

#### What version of bazel are you using?
```
Build label: 4.1.0
Build target: bazel-out/darwin-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Fri May 21 11:16:55 2021 (1621595815)
Build timestamp: 1621595815
Build timestamp as int: 1621595815
```

#### What version of the library are you using?
`aac6dec2c8d55da2b2c2689b7a2afe44b691555cab32e2eaa2bdd29627d950e9`

## Any other comments?
I understand that this is not really a problem with `rules_typescript_proto` but perhaps there is some small changes that could be made here to make it compatible with Bazel 4.1.0.

**Comment by Mista-Ree** [comment]
I have raised a PR which makes the aforementioned change. The change has only been made to the src directory as I couldn't get some of the test rules to build after switching `ts_library` to `ts_project`.

**Comment by xnerhu** [comment]
I get `Error: Expected package major version to equal @build_bazel_rules_nodejs major version
    @bazel/jasmine - 3.0.0
    @build_bazel_rules_nodejs - 4.1.0`

**Comment by pfgallagher** [comment]
Also getting this issue. Should be as simple as updating the `@bazel` deps, unless there are breaking changes? Happy to open a PR for this, if you'd like @Dig-Doug.

**Comment by Dig-Doug** [comment]
@pfgallagher - If you have a fix for this that would be awesome, thanks!

**Comment by bazaglia** [comment]
I still have the same issue @Mista-Ree described even when using @pfgallagher's fork on `update-bazel` branch. I noticed it only happens if I set the `tsconfig` property on my `ts_project`. Then I get:

```
Compiling TypeScript (devmode) @rules_typescript_proto//src:change_import_style_lib [for host] failed: (Exit 1): tsc_wrapped.sh failed: error executing command bazel-out/host/bin/external/rules_typescript_proto_deps/@bazel/typescript/bin/tsc_wrapped.sh @@bazel-out/host/bin/external/rules_typescript_proto/src/change_import_style_lib_es5_tsconfig.json
Compilation failed Error: ENOENT: no such file or directory, open '/private/var/tmp/<some-path-here>/external/rules_typescript_proto_deps/node_modules/typescript/lib/lib.es2021.string.d.ts'
```

But if I remove the `tsconfig` and let it use the `tsconfig.json` I have in my local folder it passes this point but returns this other error instead:

```
<some-path-here>/grpc/index.ts(8,30): error TS2307: Cannot find module 'protobuf/provider_a_pb' or its corresponding type declarations.
<some-path-here>/grpc/index.ts(9,34): error TS2307: Cannot find module 'protobuf/provider_a_grpc_pb' or its corresponding type declarations.
```

If I compile the typescript_proto_library and typescript_grpc_node_library it works and I see the targets created in my bazel-bin folder. But when I specify it as deps for a `ts_project`, it fails with the error above. I'm doing the imports in the following way:

```
import { SampleReply } from '<my-workspace-name>/protobuf/provider_a_pb';
```

Either I've missed something or even with @pfgallagher's last commits, I can assume this project isn't functional in the latest version of Bazel

**Comment by Dig-Doug** [comment]
Closing after #169
