### ISSUE TITLE
Issue referencing from external project

### ISSUE THREAD

**Issue by eordano** [Dig-Doug/rules_typescript_proto#8]
I'm getting this issue:
`protos/BUILD:25:1: every rule of type typescript_proto_library implicitly depends upon the target '@rules_typescript_proto_deps//ts-protoc-gen/bin:protoc-gen-ts', but this target could not be found because of: no such package '@rules_typescript_proto_deps//ts-protoc-gen/bin': BUILD file not found in directory 'ts-protoc-gen/bin' of external repository @rules_typescript_proto_deps. Add a BUILD file to a directory to mark it as a package.
`

**Comment by yihanzhen** [comment]
Hey @eordano I'm seeing exactly the same issue now even though I am pretty sure it didn't use to be a problem for me. Do you remember how you fixed this?

**Comment by eordano** [comment]
I think it was a problem with the versions of bazel, rules_nodejs, and this project. At the time, rules_nodejs was not ready for bazel 1; I eventually reverted back to using a pre-1 version of bazel. I am no longer hacking on the project where I had this problem...
